### PR TITLE
Add missing unittest

### PR DESCRIPTION
**Pull request by chhsiao90**
Hi @mike820324 , please help review~

### CODE REVIEW

**Comment by chhsiao90** [comment]
uh... weird, the tui seems not modified but the test failed... I'll fix that..

**Comment by chhsiao90** [comment]
Ohh.... it's screen length problem... I will find a way to bypass that!

**Comment by mike820324** [comment]
Good catch, if every thing works fine, would you mind merging the two commits into one and force push to this PR?

**Comment by chhsiao90** [comment]
Done~

**Comment by mike820324** [comment]
Merged thanks

**Pull request merged**
