### PR TITLE
Resolved #204: Display TLS Information

### LINKED ISSUE #204: [Proposal]: Record tls related information and display at viewer
Like tls version, sni, alpn, cipher

### PR DESCRIPTION
**Pull request by chhsiao90**

### CODE REVIEW

**Comment by mike820324** [comment]
That is quick, I'll take some time to review this. Thanks.

**Comment by chhsiao90** [comment]
Refs: #204

**Comment by mike820324** [comment]
Force push due to v0.4.1 hotfix release.

Should fix the test failed.

**Review by mike820324 — COMMENTED** [review]
LGTM, the `Serializable` class looks really good. Just one question.
- Any reasons to add the `kwargs` to `HttpRequest`, `HttpResponse`, `TlsInfo` and  `ViewContext`. Backward compatible?

**Comment by chhsiao90** [comment]
> LGTM, the Serializable class looks really good. Just one question.
> 
> Any reasons to add the kwargs to HttpRequest, HttpResponse, TlsInfo and ViewContext. Backward compatible?

Yes, for backward compatibility!

**Pull request merged**
