### PR TITLE
Resolved #147: Add Server state and related API.

### LINKED ISSUE #147: [Proposal]: Adding server state related API and ServerContext
### API List
- `init_server_state(config)``: initialize server state. ex cert_store and interceptor
- `get_server_state()`: get ServerContext.
### ServerContext:
- **config**: user pass in and should not be modifed.
- **interceptor**: there should only be one interceptor instance in the proxy server. And the interceptor is immutable after it is created.
- **cert_store**: should be one cert_store. But the cert_store will mutate.
- (optional) **io_loop**: there will be only one io_loop instance. Currently we use curr_loop() to get the io_loop.

ex. 

``` python
# server init
def proxy_main():
  config = parse_config(args)
  init_server_state(config)
  start_events_server()
  start_proxy_server()
```

``` python
# get server state
def __init__(self):
   self.config = get_server_state().config
   self.interceptor = get_server_state().interceptor
   self.cert_store = get_server_state().cert_store
```
## Layer Refinement:

The following are the reason that I decide to refine the LayerManger and LayerContext.

When we create the initial layer context, we already know which kind of layer mode we want this layer to start. In proxy.py, config is the indicator; meanwhile, in replay.py, the class itself is the indicator. 

So the actual problem becomes that application/http1.py and application/http2.py will need to know which mode the current layer is. In this case, I think putting a mode field in LayerContext would be a better way. 
### LayerManager:

The functions of `layer_manager` should be slightly modified.
### LayerContext:

Based on the ServerState changed, the LayerContext will have to slightly modified.
- remove `config` and `interceptor` field.
- add mode to indicate which entry point we want to get in. 
  - "replay
  - "socks"
  - "transparent"

### PR DESCRIPTION
**Pull request by mike820324**
- Add ServerContext
- Add `init_server_state` and `get_server_state`
- Add server_state parameter when initialize application.layer instance.
- Update unittest.
- Some code cleanup.

### CODE REVIEW

**Comment by mike820324** [comment]
@chhsiao90  Help me review thanks.

**Comment by mike820324** [comment]
I will update unittest for server state later.

**Comment by chhsiao90** [comment]
Great work! LGTM~

Had some suggestion about the global state of server_state. (Global state is hard to maintain!)
How I think to remove the global state of server_state
- Remove the global state in `server_state.py` (init_server_state just return `ServerContext`, don't keep the instance) [CodeReference](https://github.com/mike820324/microProxy/blob/server-state-%23147/microproxy/server_state.py#L28-L46)
- Init server_state instance and pass `ServerContext` to `ProxyServer` in proxy.py as its initialize field [CodeReference](https://github.com/mike820324/microProxy/blob/server-state-%23147/microproxy/proxy.py#L11-L15)
- Call run_layers with the server_state instance in `ProxyServer` [CodeReference](https://github.com/mike820324/microProxy/blob/server-state-%23147/microproxy/proxy.py#L25)

And the `layer_manager` in `ProxyServer` I think we could remove `self.layer_manager = layer_manager` in `__init__` method.
Because layer_manager had changed from object to a module, it's not object anymore, so I think there is no need to assign it to ProxyServer as its field.

How do you think :)

**Comment by mike820324** [comment]
@chhsiao90 I have modified the code based on the previous review.

**Review by chhsiao90 — APPROVED** [review]
LGTM~

**Comment by mike820324** [comment]
Thanks.
You have used the new github feature. XD

**Comment by chhsiao90** [comment]
Yeah, it's cool~ XD

**Comment by chhsiao90** [comment]
There is no reject options, so sad...

**Comment by mike820324** [comment]
Don't reject me\ QAQ/

**Pull request merged**
