### PR TITLE
Gviewer upgrade #169

### LINKED ISSUE #169: [TUIViewer]: Upgrade GViewer to v3.0.0
I planned release GViewer v3.0.0 recently.
That could support functionality for: #155 , #116 

Do you have any other idea or suggestion that could be implement in gviewer that microproxy need?

### PR DESCRIPTION
**Pull request by chhsiao90**
Resolved #169

### CODE REVIEW

**Comment by chhsiao90** [comment]
Please enjoy it~

**Comment by mike820324** [comment]
Good work. One thing to ask is that the urlencoded json/xml format, does not apply the pygments highlight. Is is the expected behaviors?

**Comment by chhsiao90** [comment]
Yes, currently, which lexer to be used is depends on which formatter is used.

**Comment by chhsiao90** [comment]
Currently, the pygments is implement in tui, so the only thing tui could know is which formatter used to format the body.
I would try implement it in formatter so that it will colorized the body more correctly.
But maybe it would wait for the gviewer upgrade merged

**Comment by mike820324** [comment]
LGTM, is it still WIP?

**Comment by chhsiao90** [comment]
No, ready to merge
Previous push is just for rebase

**Comment by mike820324** [comment]
Merged, thanks.

**Pull request merged**
