### PR TITLE
[WIP]: Refine Unittest #135

### PR DESCRIPTION
**Pull request by mike820324**
This is a tracking PR for unittest update.
- [ ] layer:
  - [x] layer manager
  - [x] socks
  - [x] transparent
  - [x] replay
  - [x] forward
  - [ ] tls
  - [x] http1
  - [x] http2
- [ ] protocol:
  - [ ] tls
  - [x] http1
  - [x] http2
- [ ] cert store
- [ ] iostream
  - [ ] MicroProxyIOStream
  - [ ] MicroProxySSLIOStream
- [ ] command line related test:
  - [ ] config 
  - [ ] command line options
- [ ] plugin system
  - [ ] watch dog
  - [ ] plugin script request/response

### CODE REVIEW

**Comment by mike820324** [comment]
Add MicroProxyIOStreamTest.

**Comment by mike820324** [comment]
Add start_tls test for MicroProxyIOStream.

**Comment by mike820324** [comment]
Almost the same as before.

**Comment by mike820324** [comment]
Add command line options check just like mitmproxy did. So that we won't by accident change the command line interface.

**Comment by chhsiao90** [comment]
I found that more open source project that use the pattern: TestCamelCase for class name than CamelCaseTest.
So I rename every unittest class for match the pattern.
And we would follow this pattern in the future.

**Comment by chhsiao90** [comment]
Please help rebase it and I will pull it after you done! haha

**Comment by chhsiao90** [comment]
@mike820324 , do you have local modification on this branch?
Let me do the rebase because I'm afraid there is conflict in it!

**Comment by mike820324** [comment]
Please rebase, I'll stash the local modification.

**Comment by mike820324** [comment]
When you finished, ping me, tks.

**Comment by chhsiao90** [comment]
@mike820324 , rebase done!

**Comment by mike820324** [comment]
Thanks, will add new test up.

**Comment by mike820324** [comment]
Update socks layer test.

**Comment by mike820324** [comment]
Rebase needed.

**Comment by mike820324** [comment]
@chhsiao90 
when the following checklist is done, I would like to issue a first merge. Currently, this PR is become too big that when some other issue merge to master, it would be very hard to rebase.
- http1 layer
- http2 layer
- replay layer
- transparent layer
- iostream

**Comment by chhsiao90** [comment]
Agreed!

**Comment by chhsiao90** [comment]
@mike820324 
my part done for http1/http2/replay !

**Comment by mike820324** [comment]
I'll finish the rest of the test on the weekend.

**Pull request merged**
