### PR TITLE
Resolved #151: Add command line options to specify the max width of summary view.

### LINKED ISSUE #151: [TUIViewer]: Resize url size based on window size
When the terminal size is not longer than url, the whole url will be in the new line. 
It would be better if the url can be changed into the following format when the line is too long.

https://google.com/.....

Also, we can also add a width size limit, when the terminal size is less than that limit, just change the line.

The standard terminal width is 80, which may be a reasonable number.

### PR DESCRIPTION
**Pull request by mike820324**
Add new command line option for tui-viewer to specify the max width of summary view.
- max-width: default to 80.

### CODE REVIEW

**Comment by mike820324** [comment]
Or maybe using the following module to determine the width of the current terminal. https://pypi.python.org/pypi/backports.shutil_get_terminal_size

**Comment by chhsiao90** [comment]
How is mitmproxy work on this?

**Comment by mike820324** [comment]
Using get_terminal_size to get the width when tui is open.

**Comment by chhsiao90** [comment]
LGTM :)

**Pull request merged**
