### PR TITLE
Publish log #116

### LINKED ISSUE #116: [Proposal]: Export microproxy server logger to viewer
I would like to propose  a new feature that will add a new zmq channel to viewer so that the viewer can receive the loggin information from the proxy server.

### PR DESCRIPTION
**Pull request by chhsiao90**
Resolved #116 

Create PR for record and discussion.
And thanks for your following commit to clean up the code!

### CODE REVIEW

**Comment by mike820324** [comment]
LGTM.

**Comment by mike820324** [comment]
This branch need to rebase. It seems like the viewer part has some conflict to fix.

**Comment by chhsiao90** [comment]
Rebased!
I need upgrade gviewer to next version that fixed some select index indicator information problem.

**Comment by chhsiao90** [comment]
Upgraded! ready for merged~

**Comment by mike820324** [comment]
I have rebased this branch again to current master.

**Pull request merged**
