### PR TITLE
close #28

### LINKED ISSUE #28: Config Log Level
We should add new field to config the log level instead of hard coded in the source code.

### PR DESCRIPTION
**Pull request by chhsiao90**
add log level config, update config for only load config file once

### CODE REVIEW

**Comment by mike820324** [comment]
Thanks bro, I will check it out later.

**Comment by mike820324** [comment]
I may need to postpone this merge request since there are some points that I need to discuss with you.

The following are my thoughts.
First, the current config file should be used only by the proxy process. As for the viewer process, it should be the viewer itself to handle the configurations. Since one day we may separate the viewer into another repos(reduce the dependencies of this project or using another programming language).

Second, in this implementation,  you separate log config by  module. 
My concern is that when this project becomes bigger , isn't the configuration of this part will also becomes larger and finally too complicate to config. Sort of breaking the initial goal of this PR, isn't it ;)
What I think is that the log level part should only be config in one place, and all the proxy process will follow the log level.

**Comment by chhsiao90** [comment]
Please see my response in following paragraph!
It's a good concern and I will reply you with my thought!

> First, the current config file should be used only by the proxy process. As for the viewer process, it should be the viewer itself to handle the configurations. Since one day we may separate the viewer into another repos(reduce the dependencies of this project or using another programming language).

But currently, viewer still in the same project, so it still need config.
So I think it doesn't matter that it used the same config now.

> My concern is that when this project becomes bigger , isn't the configuration of this part will also becomes larger and finally too complicate to config. Sort of breaking the initial goal of this PR, isn't it ;)
> What I think is that the log level part should only be config in one place, and all the proxy process will follow the log level.

We could just config logger that need to config without config all logger.
If we hadn't set up a custom logger for some module, it will used root logger.
So I think the complexity is opt to us.

**Comment by chhsiao90** [comment]
BTW, I follow the [https://github.com/waffleio/waffle.io/wiki/Recommended-Workflow-Using-Pull-Requests-&-Automatic-Work-Tracking](url) to set up waffle flow.

I think there is some point:
1. We create branch with the pattern: 21-xxxxxx or xxxxxx-#21 to connect the branch to issue 21 and it will also update issue status to In Progress automatically
2. I think ready means ready to be work on, and should be before In Progress
3. I moved Pull Request Label to Review Column(Including Collaborator and Contributor), that mean any pull request had title "close #num" will connect to specific issue and update the issue status to Review.

Please take a look and give me feedback if any, thank you.

**Comment by mike820324** [comment]
Looks great, let's follow this pattern. And I will add this to the Issue #6 documentation too.

**Comment by mike820324** [comment]
> We could just config logger that need to config without config all logger.
> If we hadn't set up a custom logger for some module, it will used root logger.
> So I think the complexity is opt to us.

So what you mean is that we can just config the logger_root, and the other logger type will just follow the logger_root settings if we didn't config them?

**Comment by chhsiao90** [comment]
> So what you mean is that we can just config the logger_root, and the other logger type will just follow the logger_root settings if we didn't config them?

That's right!

**Comment by mike820324** [comment]
OK, then this PR may ready to go.

**Comment by mike820324** [comment]
One more things, just curious about the logger section and handler section.
The keys field of the above sections is for other subsections?
ex.

```
[logger]
keys=root,proxy,http,viewer
[logger_root]
...
[logger_proxy]
...
[logger_http]
...
```

Is it the native support for ConfigParser, looks pretty cool.

**Comment by chhsiao90** [comment]
> One more things, just curious about the logger section and handler section.
> The keys field of the above sections is for other subsections?

I think it's logging.config implementation.
But as I know, logging.config use ConfigParser to load the config.
So maybe ConfigParser provide some convenient api to handle this situation.

**Comment by mike820324** [comment]
Okay, I now understand that this config file will be feed to `logging.config.fileConfig` so when we call getlogger, we can get the proper logger type.

Now it make more sense to me why the config layout is looking like this.

**Pull request merged**
