### PR TITLE
Resolved #218: add default value for mpdump.

### LINKED ISSUE #218: [mpdump]: mpdump should have default argument defined
When I tried the latest version mpdump on master with following steps
```
pip install . -U
mpdump
```

It display error as
```
Traceback (most recent call last):
  File "/Users/han-pc/.pyenv/versions/mp/bin/mpdump", line 11, in <module>
    load_entry_point('microProxy==0.4.1+dev', 'console_scripts', 'mpdump')()
  File "/Users/han-pc/.pyenv/versions/2.7.11/envs/mp/lib/python2.7/site-packages/microproxy/command_line.py", line 222, in mpdump
    config = parse_config(config_field_info)
  File "/Users/han-pc/.pyenv/versions/2.7.11/envs/mp/lib/python2.7/site-packages/microproxy/config.py", line 140, in parse_config
    verify_config(config_field_info, config)
  File "/Users/han-pc/.pyenv/versions/2.7.11/envs/mp/lib/python2.7/site-packages/microproxy/config.py", line 113, in verify_config
    raise KeyError("missing config field: [{0}]".format(",".join(missing_fields)))
KeyError: 'missing config field: [viewer_port,proxy_host,events_port]'
```

I think the error shouldn't be displayed that it need pre-defined default config.

### PR DESCRIPTION
**Pull request by mike820324**
Add default value for the following options.

- proxy-host
- event-channel
- viewer-channel

### CODE REVIEW

**Comment by mike820324** [comment]
@chhsiao90  Please review, thanks.

**Comment by chhsiao90** [comment]
Should tui-viewer had same config argument as console?
tui-viewer had viewer-channel and event-channel
but console-viewer had host, viewer-port, event-port

**Comment by mike820324** [comment]
Good point, we should open an issue discussing this part.

**Comment by mike820324** [comment]
Or just using the same issue, I'll change the title of the issue and change the PR into WIP

**Comment by mike820324** [comment]
I'll merged this first and fire another issue discussing the mpdump interface.

**Pull request merged**
