### PR TITLE
Enter ForwardLayer when encounter websocket upgrade

### LINKED ISSUE #115: [Proposal]: Adding websocket
Websocket support.

Currently, microproxy can not properly deal with website that use websocket.

### PR DESCRIPTION
**Pull request by chhsiao90**
Resolved #115 

Still work in progress.
Please help review and advice if there is any better solution!

### CODE REVIEW

**Comment by mike820324** [comment]
I'll look at it tonight. But remember to rebase to current master.

**Comment by chhsiao90** [comment]
Yeah, I will!

**Comment by mike820324** [comment]
Just curious, is it possible to change the callback style into yielding future just like SocksLayer does in Http1Layer.

If we can change into the yielding style, maybe we can remove the `gen.timeout` part.

**Comment by chhsiao90** [comment]
Currently, remove gen.timeout is ok with callback style.
I had removed it!

**Comment by mike820324** [comment]
OKOK, Great job.

**Comment by chhsiao90** [comment]
Update into sequential style.
Please help review, thanks!

**Comment by mike820324** [comment]
wow, LGTM.

**Comment by mike820324** [comment]
Merged thanks.

**Pull request merged**
