### PR TITLE
Implement http2 replay

### LINKED ISSUE #136: Implement Replay with HTTP2
Need following tasks
- [x] Refactor http2layer to extract protocol relative code into another module
- [x] ReplayLayer would handle destination tls handshaking for replay
- [x] Handle replay event with scheme: h2

### PR DESCRIPTION
**Pull request by chhsiao90**
Resolved #136

### CODE REVIEW

**Comment by chhsiao90** [comment]
@mike820324 
Please help review it ,thank you!

**Comment by chhsiao90** [comment]
Found connect to twitter will have some exception.
Need handle this, and will merge it after fix it.

**Comment by mike820324** [comment]
Is this PR still WIP??

**Comment by chhsiao90** [comment]
Yeah, still need fix reporter's problem

**Comment by mike820324** [comment]
OK, remember to rebase to current master thanks.

**Comment by chhsiao90** [comment]
Update for some http2 event handling, please help review it, thanks!

**Comment by mike820324** [comment]
LGTM, merged. Thanks.

**Pull request merged**
